name: Resource Stress Test

on:
  workflow_dispatch:
    inputs:
      job_count:
        description: 'Number of parallel attackers (max 20)'
        required: true
        default: '15'

jobs:
  attack-job:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Tạo ra một danh sách các job dựa trên input
        # Sử dụng một cách khác để tạo mảng động, tương thích hơn
        instance: ${{ fromJson(format('[{0}]', toJSON(range(1, add(inputs.job_count, 1))))) }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests

    - name: Run Resource Attack Test
      # Đổi tên file thực thi thành slowloris_tester.py (vì chúng ta đã ghi đè lên file đó)
      run: python slowloris_tester.py
