name: Resource Stress Test

on:
  # Cho phép chạy thủ công từ tab Actions
  workflow_dispatch:

jobs:
  attack-job:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      # Chạy song song 15 "máy ảo" tấn công.
      # Con số này là cố định nhưng đảm bảo workflow chạy được.
      matrix:
        instance: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests

    - name: Run Resource Attack Test
      # Tên file Python vẫn là slowloris_tester.py vì chúng ta đã ghi đè lên nó
      run: python slowloris_tester.py
